drop policy if exists cursos_aceitos_leitura on publico.cursos_aceitos;
drop policy if exists documentos_update_remocao on publico.documentos;
drop policy if exists documentos_insert on publico.documentos;
drop policy if exists documentos_select on publico.documentos;
drop policy if exists titulos_declarados_select on publico.titulos_declarados;
drop policy if exists titulos_declarados_insert on publico.titulos_declarados;
drop policy if exists titulos_declarados_update on publico.titulos_declarados;
drop policy if exists titulos_declarados_delete on publico.titulos_declarados;
drop policy if exists cursos_declarados_select on publico.cursos_declarados;
drop policy if exists cursos_declarados_insert on publico.cursos_declarados;
drop policy if exists cursos_declarados_update on publico.cursos_declarados;
drop policy if exists cursos_declarados_delete on publico.cursos_declarados;
drop policy if exists vinculos_declarados_select on publico.vinculos_declarados;
drop policy if exists vinculos_declarados_insert on publico.vinculos_declarados;
drop policy if exists vinculos_declarados_update on publico.vinculos_declarados;
drop policy if exists vinculos_declarados_delete on publico.vinculos_declarados;
drop policy if exists inscricoes_update_propria on publico.inscricoes;
drop policy if exists inscricoes_select_propria on publico.inscricoes;
drop policy if exists candidatos_update_proprio on publico.candidatos;
drop policy if exists candidatos_insert_proprio on publico.candidatos;
drop policy if exists candidatos_select_proprio on publico.candidatos;
drop function if exists publico.minha_inscricao_editavel_id();
drop function if exists publico.minha_inscricao_id();
