-- Fase 2 · Catálogo de cursos e certificações pontuáveis por Grupo (Anexo I, item 2.1).
-- GERADO por supabase/seed/gerar_cursos_pontuaveis.py. Lista exemplificativa (item 2.1, última linha):
-- cursos fora dela podem pontuar por deliberação motivada da Comissão; o motor apenas sinaliza.
-- Reversão: supabase/rollback/20260922100000_catalogo_cursos_pontuaveis.down.sql
insert into interno.cursos_pontuaveis (grupo, denominacao) values
  ('A', 'Alvenaria Estrutural'),
  ('A', 'AutoCAD Avançado'),
  ('A', 'Autodesk Civil 3D'),
  ('A', 'Básico de Licitações e Contratos'),
  ('A', 'Compliance'),
  ('A', 'Eberick'),
  ('A', 'Estudo Técnico Preliminar (ETP)'),
  ('A', 'Excel Avançado'),
  ('A', 'Geotecnologias (GPS, RTK, Drones)'),
  ('A', 'Gestão e Fiscalização de Contratos'),
  ('A', 'Portal de Compras do Governo Federal'),
  ('A', 'QiBuilder'),
  ('A', 'Revit'),
  ('A', 'SEI Avançado'),
  ('A', 'SEI Básico'),
  ('A', 'Termo de Referência (TR)'),
  ('A', 'TQS'),
  ('B', 'Básico de Licitações e Contratos'),
  ('B', 'BPM, gestão de processos, melhoria contínua'),
  ('B', 'Canva'),
  ('B', 'Compliance'),
  ('B', 'ETP'),
  ('B', 'Excel Avançado'),
  ('B', 'Gestão e Fiscalização de Contratos'),
  ('B', 'Governança pública e corporativa'),
  ('B', 'MS Project'),
  ('B', 'Planejamento estratégico, indicadores/KPIs, OKRs'),
  ('B', 'PMO'),
  ('B', 'PMP/PgMP, PRINCE2, Scrum, Agile, Kanban ou certificações equivalentes'),
  ('B', 'Power BI'),
  ('B', 'Power Point'),
  ('B', 'Primavera'),
  ('B', 'SEI Avançado'),
  ('B', 'SEI Básico'),
  ('B', 'TR'),
  ('C', 'Agente de Contratação'),
  ('C', 'Aplicação de Sanções Administrativas'),
  ('C', 'AutoCAD'),
  ('C', 'Capacitação em orçamentação de obras civis (SINAPI/SICRO/GOINFRA)'),
  ('C', 'Compliance Público'),
  ('C', 'Elaboração de ETP'),
  ('C', 'Elaboração de TR'),
  ('C', 'Excel Avançado'),
  ('C', 'Gestão e Fiscalização de Contratos'),
  ('C', 'LGPD'),
  ('C', 'Licitações e Contratos — Lei nº 14.133/2021'),
  ('C', 'Mapeamento de Processos'),
  ('C', 'MS Project'),
  ('C', 'Orçamento Público'),
  ('C', 'Pesquisa de Preços'),
  ('C', 'Planejamento de Contratação'),
  ('C', 'PMO'),
  ('C', 'Portal de Compras do Governo Federal'),
  ('C', 'Pregão Eletrônico'),
  ('C', 'Primavera'),
  ('C', 'Redação Oficial'),
  ('C', 'Registro de Preços'),
  ('C', 'Revit'),
  ('C', 'SEI Avançado'),
  ('C', 'SEI Básico'),
  ('C', 'Transparência Pública'),
  ('C', 'Termos de Ajustes e Convênios'),
  ('C', 'Tomada de Contas Especial'),
  ('C', 'Utilização de bases SINAPI/SICRO/GOINFRA')
on conflict do nothing;
